spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: projeto-emilly-microservices
      password: ms-ecok-eer

server:
  port: 8761

 #configuração do eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false #buscar os registro  falso, quem faz isso  o getway